### ISSUE TITLE
Error when teleporting on Spigot Side

### ISSUE THREAD

**Issue by Taystee13** [savagedevllc/BungeeTpa#1]
![image](https://github.com/savagedevllc/BungeeTpa/assets/145575916/4492932f-3d10-4469-8aa0-6d04f835c3a5)

**Comment by SavageAvocado** [comment]
Whoops, I forgot older server versions come with older versions of Gson. I'll have that fixed in a bit.

**Comment by SavageAvocado** [comment]
Fixed! Thanks for reporting.
